OC_GET = (
    "all",
    "events",
    "clowdapp",
    "clowdenvironment",
    "clowdjobinvocation",
    "pod",
    "pods",
    "project",
    "secret",
)

OC_ACTIONS = {
    # Basic Commands:
    "login": tuple(),
    "new_project": tuple(),
    "new_app": tuple(),
    "status": tuple(),
    "project": tuple(),
    "projects": tuple(),
    "explain": tuple(),
    # Build and Deploy Commands:
    "rollout": tuple(),
    "rollback": tuple(),
    "new_build": tuple(),
    "start_build": tuple(),
    "cancel_build": tuple(),
    "import_image": tuple(),
    "tag": tuple(),
    # Application Management Commands:
    "create": tuple(),
    "apply": tuple(),
    "get": OC_GET,
    "describe": tuple(),
    "edit": tuple(),
    "set": tuple(),
    "label": tuple(),
    "annotate": tuple(),
    "expose": tuple(),
    "delete": tuple(),
    "scale": tuple(),
    "autoscale": tuple(),
    "secrets": tuple(),
    "serviceaccounts": tuple(),
    # Troubleshooting and Debugging Commands:
    "logs": tuple(),
    "rsh": tuple(),
    "rsync": tuple(),
    "port_forward": tuple(),
    "debug": tuple(),
    "exec": tuple(),
    "proxy": tuple(),
    "attach": tuple(),
    "run": tuple(),
    "cp": tuple(),
    "wait": tuple(),
    # Advanced Commands:
    "adm": tuple(),
    "replace": tuple(),
    "patch": tuple(),
    "process": tuple(),
    "extract": tuple(),
    "observe": tuple(),
    "policy": tuple(),
    "auth": tuple(),
    "image": tuple(),
    "registry": tuple(),
    "idle": tuple(),
    "api_versions": tuple(),
    "api_resources": tuple(),
    "cluster_info": tuple(),
    "diff": tuple(),
    "kustomize": tuple(),
    # Settings Commands:
    "logout": tuple(),
    "config": tuple(),
    "whoami": tuple(),
    "completion": tuple(),
    # Other Commands:
    "ex": tuple(),
    "help": tuple(),
    "plugin": tuple(),
    "version": tuple(),
}
